services:
  proxy:
    build: .
    container_name: proxy-openwebui
    ports:
      - "9090:9090"
    environment:
      - VERTEXAI_PROJECT=${VERTEXAI_PROJECT}
      - VERTEXAI_LOCATION=${VERTEXAI_LOCATION}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/cerdential-gcp.json
      - VERTEXAI_AVAILABLE_MODELS=${VERTEXAI_AVAILABLE_MODELS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./cerdential-gcp.json:/app/cerdential-gcp.json:ro
    restart: unless-stopped