services:
  proxy:
    build: .
    container_name: proxy-openwebui
    ports:
       - "${PORT}:${PORT}"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VERTEXAI_PROJECT=${VERTEXAI_PROJECT}
      - VERTEXAI_LOCATION=${VERTEXAI_LOCATION}
      - VERTEXAI_ANTHROPIC_VERSION=${VERTEXAI_ANTHROPIC_VERSION}
      - VERTEXAI_AVAILABLE_MODELS=${VERTEXAI_AVAILABLE_MODELS}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/cerdential-gcp.json
    volumes:
      - ./cerdential-gcp.json:/app/cerdential-gcp.json:ro
    restart: unless-stopped